[package]
name = "dice"
version = "0.1.0"
authors = ["Brian McCallister <bmccallister@groupon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
structopt = "0.3.5"
nom = "5.0.1"
pest = "2.1.2"
pest_derive = "2.1.0"
anyhow = "1.0.25"
exitfailure = "0.5.1"
